---
title: "Nick Visualizations"
output: html_document
date: "2026-04-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load Libraries:
```{r}
library(tidyverse)
library(knitr)
library(readr)
library(ggrepel)
library(sf)
library(scales)
library(ggh4x)
```

Load Data:
```{r}
statcast <- read_csv("statcast.csv")
```

Save Combined Data:
```{r}
write_csv(statcast, "statcast.csv")
```

Remove Unneeded Cols:
```{r}
statcast_clean <- statcast %>%
  select(-matches(".*deprecated$"), -spin_dir, -umpire) %>% #Remove deprecated numbers
  select(-matches("fielder_[0-9]")) %>% 
  select(-matches("on_[1-3]b$")) %>%
  select(-matches("[io]f_fielding_alignment")) %>%
  select(-matches("delta_.*")) %>%
  select(-matches("intercept_ball_.*")) %>%
  select(-matches(".*_days_since_.*"), -matches(".*_days_until_.*")) %>%
  select(-age_pit_legacy, -age_bat_legacy) %>%
  select(-matches("api_.*")) %>%
  select(-woba_value, -woba_denom) %>%
  select(-matches(".*score.*"))
  
statcast_clean <- statcast_clean %>%
  drop_na(pitch_type) %>%
  filter(game_type=="R")
#write_csv(statcast_clean, "statcast_clean.csv")
```

Format Columns Where Needed:
```{r}
statcast_clean <- statcast_clean %>%
  mutate(pitch_type = as.factor(pitch_type)) %>%
  mutate(description = as.factor(description)) %>%
  mutate(zone = as.factor(zone)) %>%
  mutate(p_throws = as.factor(p_throws)) %>%
  mutate(pitch_type = recode(pitch_type,
                             "FF" = "4-Seam",
                             "SI" = "2-Seam",
                             "FC" = "Cutter",
                             "FS" = "Splitter",
                             "CH" = "Changeup",
                             "KC"= "Knuckle Curve",
                             "CU" = "Curveball",
                             "SL" = "Slider",
                             "ST" = "Sweeper"
                             )) %>%
  mutate(pitch_type = factor(pitch_type, levels = c(
    "4-Seam", "2-Seam", "Cutter", "Splitter", "Changeup", "Knuckle Curve", "Curveball", "Slider", "Sweeper")))
```

Color Assignments:
```{r}
pitch_type_colors <- c(
  "4-Seam" = "#8B2323",
  "2-Seam" = "#FF3030",
  "Cutter" = "#CD6839",
  "Splitter" = "#FA8072",
  "Changeup" = "#97FFFF",
  "Knuckle Curve" = "#00B2EE",
  "Curveball" = "#4F94CD",
  "Slider" = "#3A5FCD",
  "Sweeper" = "#473C8B")
```

Pitch Speed by Age:
```{r}
fastballs <- statcast_clean %>%
  select(pitch_type, age_pit, release_speed, pitch_name) %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%  
  group_by(age_pit, pitch_type) %>%
  summarise(mean_speed = mean(release_speed, na.rm=TRUE))

ggplot(fastballs, aes(x=age_pit, 
                      y=mean_speed,
                      color = pitch_type)) +
  geom_point(alpha = .5, 
             size = 2,
             color = "black") + 
  geom_smooth(se=FALSE) +
  facet_wrap(.~pitch_type, 
             nrow = 3) +
  scale_color_manual(values = pitch_type_colors) +
  force_panelsizes(rows = unit(5, "cm")) +
  labs(x = "Age", 
       y = "Average Pitch Speed (mph)", 
       color = "Pitch Type", 
       title = "Average Speed for Fastball Types at Each Recorded Age") + 
  theme(strip.text = element_blank(),
        strip.background = element_blank(),
        panel.background= element_rect(fill="gray89"),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black",
                                    fill = NA,
                                    linewidth = 1)
  )
```

Outcomes of Each Pitch Data Cleaning:
```{r}
pitch_type_outcomes <- statcast_clean %>%
  select(pitch_type, events) %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%      filter(!is.na(events)) %>%
    mutate(outcome = case_when(
    events == "double" | events == "triple" | events == "home_run" ~ "XBH",
    events == "grounded_into_double_play" | events == "strikeout_double_play" | events == "double_play" | events == "sac_fly_double_play" | events == "triple_play" | events == "sac_bunt_double_play" ~ "Double/Triple Play",
    events == "field_out" | events == "force_out" | events == "fielders_choice" | events == "fielders_choice_out" ~ "Field Out",
    events == "strikeout" ~ "K",
    events == "single" ~ "Single",
    events == "walk" | events == "hit_by_pitch" ~ "Walk/HBP",
    events == "catcher_interf"  | events == "truncated_pa" | events == "sac_bunt" | events == "sac_fly" | events == "field_error" ~ "Other"
     )) %>%
  mutate(pitch_type = factor(pitch_type, levels = c(
    "4-Seam", "2-Seam", "Cutter", "Splitter", "Changeup", "Knuckle Curve", "Curveball", "Slider", "Sweeper"))) %>%
  group_by(outcome, pitch_type) %>%
  summarize(count = n(), .groups = "drop_last") %>%
  mutate(prop = count / sum(count))
```

Outcomes of Each Pitch Visualization:
```{r}
ggplot(pitch_type_outcomes, aes(x="", y=prop, fill=pitch_type)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) + 
  facet_wrap(~outcome) +
  scale_fill_manual(values = pitch_type_colors) +
  theme(strip.background = element_blank(),
        panel.background= element_rect(fill="gray89"),
        panel.grid = element_blank(),
        panel.border = element_rect(color = "black",
                                    fill = NA,
                                    linewidth = 1),
        axis.text = element_blank(),
        axis.ticks = element_blank()
  ) +
  labs(x = NULL, y = NULL, title = "Plate Appearance Outcomes by Pitch Type", fill = "PA Outcome")

counts <- statcast_clean %>%
  select(pitch_type) %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%    group_by(pitch_type) %>%
  summarize(count=n()) %>%
  mutate(prop = count/sum(count))

ggplot(counts, aes(x="", y=prop, fill=pitch_type)) +
  geom_bar(stat="identity", width=1, color="white") +
  geom_label(data = counts, aes(y=prop, x=1.6, label=scales::percent(prop, accuracy = 0.1), color = pitch_type),
             fill = "white",
             show.legend = FALSE,
             position = position_stack(vjust = .5)) +
  coord_polar("y", start=0) +
  scale_fill_manual(values = pitch_type_colors) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",
                                    fill = NA,
                                    linewidth = 1),
        strip.background = element_blank(),
        panel.background= element_rect(fill="gray89"),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(x = NULL, y = NULL)
```

Specific Counts vs. Pitch Type:
```{r}
specific_counts <- statcast_clean %>%
  select(pitch_type, balls, strikes) %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%    mutate(batting_count = paste(balls, strikes, sep = "-")) %>%
  group_by(batting_count, pitch_type) %>%
  summarize(count = n()) %>%
  mutate(prop = count/sum(count))

ggplot(specific_counts, aes(x="", y=prop, fill=pitch_type)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  facet_wrap(~batting_count, nrow=4) +
  scale_fill_manual(values = pitch_type_colors) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",
                                    fill = NA,
                                    linewidth = 1),
        strip.background = element_blank(),
        panel.background= element_rect(fill="gray89"),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(x = NULL, y = NULL)

```

Specific Counts vs. Outcomes:
```{r}
specific_counts_outcomes <- statcast_clean %>%
  select(description, balls, strikes) %>%
  mutate(batting_count = paste(balls, strikes, sep = "-")) %>%
  filter(!is.na(description)) %>%
    mutate(outcome = case_when(
      description == "hit_into_play" ~ "Hit",
      description == "swinging_strike" | description == "swinging_pitchout" | description == "missed_bunt" ~ "Swinging K",
      description == "called_strike" ~ "Called Strike",
      description == "foul" | description == "foul_bunt" | description == "bunt_foul_tip" | description == "foul_tip" | description == "foul_pitchout" ~ "Foul",
      description == "pitchout" ~ "Pitchout",
      description == "ball" | description == "blocked_ball" | description == "hit_by_pitch" ~ "Ball/HBP",
      description == "swinging_strike_blocked" ~ "Dropped Swinging Strike")) %>%
  group_by(batting_count, outcome) %>%
  summarize(count = n()) %>%
  mutate(prop = count/sum(count))

ggplot(specific_counts_outcomes, aes(x="", y=prop, fill=outcome)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  facet_wrap(~batting_count, nrow=4) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",
                                    fill = NA,
                                    linewidth = 1),
        strip.background = element_blank(),
        panel.background= element_rect(fill="gray89"),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(x = NULL, y = NULL)

```

Pitch Type vs. Outcome
```{r}
pitch_outcomes_with_pitch_types <- statcast_clean %>%
  select(description, pitch_type) %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%
  filter(!is.na(description)) %>%
    mutate(outcome = case_when(
      description == "hit_into_play" ~ "Hit",
      description == "swinging_strike" | description == "swinging_pitchout" | description == "missed_bunt" ~ "Swinging K",
      description == "called_strike" ~ "Called Strike",
      description == "foul" | description == "foul_bunt" | description == "bunt_foul_tip" | description == "foul_tip" | description == "foul_pitchout" ~ "Foul",
      description == "pitchout" ~ "Pitchout",
      description == "ball" | description == "blocked_ball" | description == "hit_by_pitch" ~ "Ball/HBP",
      description == "swinging_strike_blocked" ~ "Dropped Swinging Strike")) %>%
  group_by(pitch_type, outcome) %>%
  mutate(pitch_type = factor(pitch_type, levels = c(
    "4-Seam", "2-Seam", "Cutter", "Splitter", "Changeup", "Knuckle Curve", "Curveball", "Slider", "Sweeper"))) %>%
  summarize(count = n()) %>%
  mutate(prop = count/sum(count))

ggplot(pitch_outcomes_with_pitch_types, aes(x="", y=prop, fill=outcome)) +
  geom_bar(stat="identity", width=1, color="white") +
  coord_polar("y", start=0) +
  facet_wrap(~pitch_type, nrow=3) +
  theme(panel.grid = element_blank(),
        panel.border = element_rect(color = "black",
                                    fill = NA,
                                    linewidth = 1),
        strip.background = element_blank(),
        panel.background= element_rect(fill="gray89"),
        axis.text = element_blank(),
        axis.ticks = element_blank()) +
  labs(x = NULL, y = NULL)
```

RHP Statcast Zones:
```{r}
zone1coords <- matrix(c(-17/2,17/2, -17/6,17/2, -17/6,17/6, -17/2,17/6, -17/2,17/2),
                      ncol = 2,
                      byrow= TRUE)
zone2coords <- matrix(c(-17/6,17/2, 17/6,17/2, 17/6,17/6, -17/6,17/6, -17/6,17/2),
                      ncol = 2,
                      byrow=TRUE)
zone3coords <- matrix(c(17/6,17/2, 17/2,17/2, 17/2,17/6, 17/6,17/6, 17/6,17/2),
                      ncol = 2,
                      byrow=TRUE)
zone4coords <- matrix(c(-17/2,17/6, -17/6,17/6, -17/6,-17/6, -17/2,-17/6, -17/2,17/6),
                      ncol = 2,
                      byrow=TRUE)
zone5coords <- matrix(c(-17/6,17/6, 17/6,17/6, 17/6,-17/6, -17/6,-17/6, -17/6,17/6),
                      ncol = 2,
                      byrow=TRUE)
zone6coords <- matrix(c(17/6,17/6, 17/2,17/6, 17/2,-17/6, 17/6,-17/6, 17/6,17/6),
                      ncol = 2,
                      byrow=TRUE)
zone7coords <- matrix(c(-17/2,-17/6, -17/6,-17/6, -17/6,-17/2, -17/2,-17/2, -17/2,-17/6),
                      ncol = 2,
                      byrow= TRUE)
zone8coords <- matrix(c(-17/6,-17/6, 17/6,-17/6, 17/6,-17/2, -17/6,-17/2, -17/6,-17/6),
                      ncol = 2,
                      byrow=TRUE)
zone9coords <- matrix(c(17/6,-17/6, 17/2,-17/6, 17/2,-17/2, 17/6,-17/2, 17/6,-17/6),
                      ncol = 2,
                      byrow=TRUE)
zone11coords <- matrix(c(0,17/2, -17/2,17/2, -17/2,0, -12.3,0, -12.3,12.3, 0,12.3, 0,17/2),
                       ncol=2,
                       byrow=TRUE)
zone12coords <- matrix(c(0,17/2, 17/2,17/2, 17/2,0, 12.3,0, 12.3,12.3, 0,12.3, 0,17/2),
                       ncol=2,
                       byrow=TRUE)
zone13coords <- matrix(c(17/2,0, 12.3,0, 12.3,-12.3, 0,-12.3, 0,-17/2, 17/2,-17/2, 17/2, 0),
                       ncol=2,
                       byrow=TRUE)
zone14coords <- matrix(c(0,-17/2, 0,-12.3, -12.3,-12.3, -12.3,0, -17/2,0, -17/2,-17/2, 0,-17/2),
                       ncol=2,
                       byrow=TRUE)

zones <- st_sfc(st_polygon(list(zone1coords)), 
                st_polygon(list(zone2coords)),
                st_polygon(list(zone3coords)),
                st_polygon(list(zone4coords)),
                st_polygon(list(zone5coords)),
                st_polygon(list(zone6coords)),
                st_polygon(list(zone7coords)),
                st_polygon(list(zone8coords)),
                st_polygon(list(zone9coords)),
                st_polygon(list(zone11coords)),
                st_polygon(list(zone12coords)),
                st_polygon(list(zone13coords)),
                st_polygon(list(zone14coords)))
areas <- st_sf(
  Strike_Zone = c("Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Zone 6", "Zone 7", "Zone 8", "Zone 9", "Zone 11", "Zone 12", "Zone 13", "Zone 14"),
  geometry = zones
)

strike_zone_data <- statcast_clean %>%
  select(pitch_type, zone, p_throws) %>%
  filter(p_throws == "R") %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%
  mutate(pitch_type = factor(pitch_type, levels = c(
    "4-Seam", "2-Seam", "Cutter", "Splitter", "Changeup", "Knuckle Curve", "Curveball", "Slider", "Sweeper"))) %>%
  filter(!is.na(zone)) %>%
  mutate(Strike_Zone = recode(zone,
                       "1" = "Zone 1",
                       "2" = "Zone 2",
                       "3" = "Zone 3",
                       "4" = "Zone 4",
                       "5" = "Zone 5",
                       "6" = "Zone 6",
                       "7" = "Zone 7",
                       "8" = "Zone 8",
                       "9" = "Zone 9",
                       "11" = "Zone 11",
                       "12" = "Zone 12",
                       "13" = "Zone 13",
                       "14" = "Zone 14")) %>%
  group_by(pitch_type, Strike_Zone) %>%
  summarize(count=n()) %>%
  mutate(percent = count/sum(count)*100)

print(areas)
plot(areas["Strike_Zone"], col = NA)

areas_with_data <- areas %>%
  left_join(strike_zone_data, by = "Strike_Zone") %>%
  group_by(pitch_type, Strike_Zone)

ggplot(areas_with_data) + 
  geom_sf(aes(fill=percent), color = "white", size = 0.2) +
  scale_fill_viridis_c(option = "mako", name = "Pitch %", na.value = "grey90", direction = -1) +
  facet_wrap(~pitch_type) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank())
```

LHP Statcast Zones:
```{r}
zone1coords <- matrix(c(-17/2,17/2, -17/6,17/2, -17/6,17/6, -17/2,17/6, -17/2,17/2),
                      ncol = 2,
                      byrow= TRUE)
zone2coords <- matrix(c(-17/6,17/2, 17/6,17/2, 17/6,17/6, -17/6,17/6, -17/6,17/2),
                      ncol = 2,
                      byrow=TRUE)
zone3coords <- matrix(c(17/6,17/2, 17/2,17/2, 17/2,17/6, 17/6,17/6, 17/6,17/2),
                      ncol = 2,
                      byrow=TRUE)
zone4coords <- matrix(c(-17/2,17/6, -17/6,17/6, -17/6,-17/6, -17/2,-17/6, -17/2,17/6),
                      ncol = 2,
                      byrow=TRUE)
zone5coords <- matrix(c(-17/6,17/6, 17/6,17/6, 17/6,-17/6, -17/6,-17/6, -17/6,17/6),
                      ncol = 2,
                      byrow=TRUE)
zone6coords <- matrix(c(17/6,17/6, 17/2,17/6, 17/2,-17/6, 17/6,-17/6, 17/6,17/6),
                      ncol = 2,
                      byrow=TRUE)
zone7coords <- matrix(c(-17/2,-17/6, -17/6,-17/6, -17/6,-17/2, -17/2,-17/2, -17/2,-17/6),
                      ncol = 2,
                      byrow= TRUE)
zone8coords <- matrix(c(-17/6,-17/6, 17/6,-17/6, 17/6,-17/2, -17/6,-17/2, -17/6,-17/6),
                      ncol = 2,
                      byrow=TRUE)
zone9coords <- matrix(c(17/6,-17/6, 17/2,-17/6, 17/2,-17/2, 17/6,-17/2, 17/6,-17/6),
                      ncol = 2,
                      byrow=TRUE)
zone11coords <- matrix(c(0,17/2, -17/2,17/2, -17/2,0, -12.3,0, -12.3,12.3, 0,12.3, 0,17/2),
                       ncol=2,
                       byrow=TRUE)
zone12coords <- matrix(c(0,17/2, 17/2,17/2, 17/2,0, 12.3,0, 12.3,12.3, 0,12.3, 0,17/2),
                       ncol=2,
                       byrow=TRUE)
zone13coords <- matrix(c(17/2,0, 12.3,0, 12.3,-12.3, 0,-12.3, 0,-17/2, 17/2,-17/2, 17/2, 0),
                       ncol=2,
                       byrow=TRUE)
zone14coords <- matrix(c(0,-17/2, 0,-12.3, -12.3,-12.3, -12.3,0, -17/2,0, -17/2,-17/2, 0,-17/2),
                       ncol=2,
                       byrow=TRUE)

zones <- st_sfc(st_polygon(list(zone1coords)), 
                st_polygon(list(zone2coords)),
                st_polygon(list(zone3coords)),
                st_polygon(list(zone4coords)),
                st_polygon(list(zone5coords)),
                st_polygon(list(zone6coords)),
                st_polygon(list(zone7coords)),
                st_polygon(list(zone8coords)),
                st_polygon(list(zone9coords)),
                st_polygon(list(zone11coords)),
                st_polygon(list(zone12coords)),
                st_polygon(list(zone13coords)),
                st_polygon(list(zone14coords)))
areas <- st_sf(
  Strike_Zone = c("Zone 1", "Zone 2", "Zone 3", "Zone 4", "Zone 5", "Zone 6", "Zone 7", "Zone 8", "Zone 9", "Zone 11", "Zone 12", "Zone 13", "Zone 14"),
  geometry = zones
)

strike_zone_data <- statcast_clean %>%
  select(pitch_type, zone, p_throws) %>%
  filter(p_throws == "L") %>%
  filter(pitch_type %in% c("4-Seam",
                             "2-Seam",
                             "Cutter",
                             "Splitter",
                             "Changeup",
                             "Knuckle Curve",
                             "Curveball",
                             "Slider",
                             "Sweeper"
                             )) %>%
  mutate(pitch_type = factor(pitch_type, levels = c(
    "4-Seam", "2-Seam", "Cutter", "Splitter", "Changeup", "Knuckle Curve", "Curveball", "Slider", "Sweeper"))) %>%
  filter(!is.na(zone)) %>%
  mutate(Strike_Zone = recode(zone,
                       "1" = "Zone 1",
                       "2" = "Zone 2",
                       "3" = "Zone 3",
                       "4" = "Zone 4",
                       "5" = "Zone 5",
                       "6" = "Zone 6",
                       "7" = "Zone 7",
                       "8" = "Zone 8",
                       "9" = "Zone 9",
                       "11" = "Zone 11",
                       "12" = "Zone 12",
                       "13" = "Zone 13",
                       "14" = "Zone 14")) %>%
  group_by(pitch_type, Strike_Zone) %>%
  summarize(count=n()) %>%
  mutate(percent = count/sum(count)*100)

print(areas)
plot(areas["Strike_Zone"], col = NA)

areas_with_data <- areas %>%
  left_join(strike_zone_data, by = "Strike_Zone") %>%
  group_by(pitch_type, Strike_Zone)

ggplot(areas_with_data) + 
  geom_sf(aes(fill=percent), color = "white", size = 0.2) +
  scale_fill_viridis_c(option = "mako", name = "Pitch %", na.value = "grey90", direction = -1) +
  facet_wrap(~pitch_type) +
  theme(axis.ticks = element_blank(),
        axis.text = element_blank())
```